config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sessions/new'

  resources :users do
    resources :donations, :only =>[:new, :create]
  end

  resources :sessions do
    resources :users, :except =>[:index]
  end


end

app/models/donation.rb
class Donation < ActiveRecord::Base
  after_create :add
  belongs_to :user
  attr_accessor :token

  private
    def add
      Stripe.api_key = "sk_test_LIeCBTv3nCs4I35yzMthkk5f"

      begin
        donation = Stripe::Charge.create(
          :amount => amount, # amount in cents, again
          :currency => "usd",
          :card => token,
          :description => User.find(self.user_id).email
        )
      rescue Stripe::CardError => e
        # The card has been declined
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :donations
  has_secure_password
  validates_presence_of :name
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

   private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
      redirect_to login_url, alert: "Not authorized!" if (current_user.id != (session[:user_id]))
    end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController


  def new
    @user = current_user
    @donation = Donation.new
  end

  def create
    # Create the charge on Stripe's servers - this will charge the user's card
    @donation = Donation.new(donation_params)
    @donation.user_id = current_user.id

    @donation.token = params[:stripeToken]

    if @donation.save
      redirect_to user_path(current_user), notice: "Payment added!"
    else
      render 'new'
    end
  end

private
  def donation_params
    params.require(:donation).permit(:amount, :stripeToken, :currency)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to session_user_path(session, user), notice: "Logged in!"
    else
      flash[:notice] = "name or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, only: [:edit, :update, :show]

  def index
      @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User was added"
      redirect_to session_user_path(session, @user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if current_user.id == @user.id
      if @user.update(user_params)
        flash[:notice] = "User updated."
        redirect_to session_user_path(session, @user)
      else
        render 'edit'
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user.id == @user.id
      if @user.destroy
        current_user.destroy
        session[:user_id] = nil
        flash[:notice] = "The user was deleted."
        redirect_to root_path
      end
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation, :stripe_token, :last_4_digits)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/new.html.erb
<%= form_for ([@user, @donation]), html: {class: "new-payment"} do |f| %>
  <% if @donation.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>
      <ul>
      <% @donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-row">
    <div class="field">
      <%= f.label :amount %><br>
      <%= f.text_field :amount %>
    </div>
  </div>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <%= f.submit(:class => "btn btn-success") %>

<% end %>

<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
  // This identifies your website in the createToken call belo
  Stripe.setPublishableKey('pk_test_oaJaDZ9Fh8uVTvJGu8d219Jc');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stripe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://js.stripe.com/v2/', 'application', 'data-turbolinks-track' => true %>
 <script type="text/javascript">

     Stripe.setPublishableKey('pk_test_oaJaDZ9Fh8uVTvJGu8d219Jc');
  </script>
  <%= csrf_meta_tags %>

</head>
  <nav class="navbar navbar-inverse fixed navbar-custom" role="navigation">
    <div class="container">
      <ul class="nav navbar-nav title">
        <% if current_user %>
          <li><%= link_to "Log out", logout_path %></li>
          <li><a>Logged in as <%= current_user.name %></a></li>
          <li><%= link_to "Make Donation", new_user_donation_path(current_user) %></li>
          <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
<body>
  <div class="container">
    <%= flash[:notice] %>
    <%= yield %><br/>

  </div>
</body>
</html>

app/views/users/_form.html.erb
<head><script type="text/javascript" src="https://js.stripe.com/v2/"></script></head>
<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('sk_test_LIeCBTv3nCs4I35yzMthkk5f');
  // ...
</script>
<div class="row">
  <div class="span6 columns">
    <fieldset>
      <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="clearfix">
          <%= f.label :name %>
          <div class="input">
            <%= f.text_field :name %>
          </div>
        </div>

        <div class="clearfix">
          <%= f.label :email %>
          <div class="input">
            <%= f.text_field :email, :class => "field" %>
          </div>
        </div>

        <div class="clearfix">
          <%= f.label :password %>
          <div class="input">
            <%= f.password_field :password, :class => "field" %>
            <% if defined? editing %>
              <span class="help-block">Leave blank to keep your current password</span>
            <% end %>
          </div>
        </div>

        <div class="clearfix">
          <%= f.label :password_confirmation %>
          <div class="input">
            <%= f.password_field :password_confirmation, :class => "field" %>
        </div>

          <%= f.hidden_field :stripe_token %>
        </div>

        <div class="actions">
          <%= f.submit(:class => "btn btn-success") %>
        </div>


      <% end %>
    </fieldset>
  </div>
</div>

app/views/users/edit.html.erb
<div class="page-header">
  <h1>Edit Profile</h1>
</div>

<%= render :partial => 'users/form', :locals => {:user => current_user, :editing => true} %>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Register</h1>
</div>

<%= render :partial => 'users/form', :locals => {:user => @user} %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= current_user.name %><br/>
  <%= current_user.email %><br/>
</p>
<br>


<br>
<p>edit or delete user</p>

<%= link_to 'Edit', edit_session_user_path(session, @user) %> |
<%= link_to 'Delete', session_user_path(session, @user), :data => {:method => "delete"} %>